language: generic
services:
  - docker

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    docker run --rm \
      -e ELECTRON_CACHE="/root/.cache/electron" \
      -e ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
      -v $PWD/node_modules:/project/node_modules \
      -v $HOME/.cache/electron:/root/.cache/electron \
      -v $HOME/.cache/electron-builder:/root/.cache/electron-builder \
      -v $PWD:/project \
      electronuserland/builder:16-wine-05.22 /bin/bash -c "whoami && ls -la /root/.cache/electron && npm install && npm run package"
  - sudo chown -R travis:travis build
  - ./scripts/package.sh
if: tag IS present

deploy:
  provider: releases
  api_key:
    secure: "pGyN7c1cTum6WxvWvCve8lG9qj114X91AFFxNuHsbQSemjLoAf8ti9ldiBHD5QrDN6Bt5QpAJOeXqVSclbvKs7JKCGTHY+U8nkXB9YH2aOqs696T6UmmobJ32mnRXs31+lFYF4raG2FKZ2R2JcFr3UJISnV0ZMDkXisfA67E1NCEMmyjdlIf3Sl5v8aRvMKjqQVS6tUqQywx1LAPk0FARvjHdgWZePbl63Tie8TO5pGFWa0kJz4c+7BzhcVJrLeoWmQrSyQwYojQwrS/l4lM29a6bI30IQEmi1POpOY8hdUKFbXBgDWIAEmeIarOFGZBSbwUvsoSVRkn/WZcqKRVuB8/Wql9WnpM7Xm6zXrXemIjyN2kDkAL0SR8gh+bq0iKU8WYW1xn8WlWi99Qipmwc6C/t4x3ZwA3PL46pHa2M1Yj6cmmrItGPDVPLQytkub4BtsONVIOi9SEmXu53oAIR2B+usSuHxrIS4MtF+AgDQY+jO2YjC5RseMEEt+jAYWRhK0CQXVmvKIj8Hp1gHNoGzlm8tekK+mVy8WqYQLA55h8AfNZWQDJuLF4pi/xJnEzOOhQVtjXqyPgvqfU7P7QaBZJKSegd62Ot2r6Q6R72fas5RqoxlCewtpFews1bmIK09nDpFcdL1bwW0cCeqf4MefiQgYodhOTc/Ncf21TGgI="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/webapp-display
    tags: true    
